name: LLM
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - python=3.10.0=h12debd9_5
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.1=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2022g=h04d1e81_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==1.4.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - appdirs==1.4.4
    - async-timeout==4.0.2
    - attrs==22.2.0
    - certifi==2022.12.7
    - charset-normalizer==3.1.0
    - click==8.1.3
    - cmake==3.26.0
    - docker-pycreds==0.4.0
    - filelock==3.10.0
    - fire==0.5.0
    - frozenlist==1.3.3
    - gitdb==4.0.10
    - gitpython==3.1.31
    - huggingface-hub==0.13.3
    - idna==3.4
    - jinja2==3.1.2
    - joblib==1.2.0
    - lit==16.0.0
    - markupsafe==2.1.2
    - mpmath==1.3.0
    - multidict==6.0.4
    - networkx==3.0
    - nltk==3.8.1
    - numpy==1.24.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - openai==0.27.2
    - packaging==23.0
    - pathtools==0.1.2
    - pip==23.0.1
    - protobuf==4.22.1
    - psutil==5.9.4
    - pyyaml==6.0
    - regex==2022.10.31
    - requests==2.28.2
    - rouge-score==0.1.2
    - sentencepiece==0.1.97
    - sentry-sdk==1.17.0
    - setproctitle==1.3.2
    - setuptools==65.6.3
    - six==1.16.0
    - smmap==5.0.0
    - sympy==1.11.1
    - termcolor==2.2.0
    - tokenizers==0.12.1
    - torch==2.0.0
    - tqdm==4.65.0
    - transformers==4.27.2
    - triton==2.0.0
    - typing-extensions==4.5.0
    - urllib3==1.26.15
    - wandb==0.14.0
    - wheel==0.38.4
    - yarl==1.8.2
prefix: /home/hdd/fujiayun/miniconda3/envs/LLM
